export const birthDoulaSkills = [
	'VBAC',
	'Multiples',
	'Premature Births',
	'Nursing/Lactation',
	'High Risk',
	'LGBTQ Families',
	'Teens',
	'Single Parent',
	'Trama Informed',
	'Families of Color',
	'Adoption',
	'People with Disabilities',
	'Water Births',
	'Home Births',
	'Advocacy in Hospital',
	'Prenatal Yoga',
	'Birth Loss',
	'Birth Termination',
]

export const postpartumDoulaSkills = [
	'Care After Cesaerean',
	'Premature Births',
	'Nursing/Lactation',
	'Cooking/Nutrition',
	'Multiples',
	'Postpartum Mood Disorders',
	'Infant CPR and First Aid',
	'Overnight Availability',
	'Care for Older Children',
	'Has Car with License and Registration',
	'People with Disabilities',
]

export const languages = [
	'English',
	'Spanish',
	'Chinese',
	'French',
	'Urdu',
	'Farsi',
	'Arabic',
	'Italian',
	'Polish ',
	'Russian',
	'Tagalog',
	'Greek ',
	'Korean',
]
